### ISSUE TITLE
Handle using 'list' as variable

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/gleam-templates#1]
Currently it fails at gleam compile time due to it clashing with the `gleam/list` import.

**Comment by lpil** [comment]
What's the error? You should be able to have a module and a variable with the same name

**Comment by michaeljones** [comment]
I'm struggling to reproduce it now. I happen just as I was getting it ready. The generated code uses `list.fold` for the for-loops and I would have though that using `list.fold` inside a function that accepts `list` as an argument would cause issues? Not sure why I'm not able to trigger it?

**Comment by lpil** [comment]
That should be valid Gleam, there may be some other conflict here

**Comment by michaeljones** [comment]
So you have have the module `list` and the variable `list` existing in the same namespace? Just want to check I'm being clear. What happens if the `list` variable is a custom type with a field called `fold` what gets referenced? 

This is the generated code for one example (not with the custom type thing described above, just with `list` as a `List(String)` by inference.)
```
import gleam/string_builder.{StringBuilder}
import gleam/list



pub fn render_builder(list list) -> StringBuilder {
    let builder = string_builder.from_string("")
    let builder = string_builder.append(builder, "<h1>My List</h1>
<ul>
")
    let builder = list.fold(list, builder, fn(builder, entry) {
            let builder = string_builder.append(builder, "
    <li>")
    let builder = string_builder.append(builder, entry)
    let builder = string_builder.append(builder, "</li>
")

        builder
})
    let builder = string_builder.append(builder, "
</ul>
")

    builder
}

pub fn render(list list) -> String {
    string_builder.to_string(render_builder(list: list))
}
```

**Comment by lpil** [comment]
That should work, aye

https://johndoneth.github.io/gleam-playground/?s=JYWwDg9gTgLgBAcwDYFMCGID0TgGcYBQoksiqGmwEBBYArgEZwBmAdnCGsKwBQ74BKOAG8CcOPxgA6KCgBuKKLhR88MAWLgAfAHxwqUgCYoGdBAQC%2BQA

**Comment by michaeljones** [comment]
Very cool! Good to know. Thanks for taking the time. Must have been something else then. I'll close this.

**Comment by lpil** [comment]
No problem! Thank you
