### ISSUE TITLE
Calling functions in a template results in extra parameters being added

### ISSUE THREAD

**Issue by lpil** [michaeljones/gleam-templates#10]
Given this template
```rust
{> import some_module

{{ some_module.function() }}
```
The generated function takes an argument called `some_module`, thinking that it was a parameter. Perhaps it could be made that parameters have to be specified up front using the `with` syntax?

**Comment by michaeljones** [comment]
Interesting point. Definitely worth handling. I guess you can work around it by passing that value in instead but that isn't ideal.

Perhaps if we parse the import list more careful then we can not make parameters for anything that is imported? Or would there be issues with that?

**Comment by lpil** [comment]
That sounds good, it reminds me of Scala Play's templates a bit.

https://www.playframework.com/documentation/2.8.x/ScalaTemplates

See the bit about template parameters

**Comment by michaeljones** [comment]
I guess it is a bit complicated by the fact that Gleam does support variables and modules with the same name? I think that came up? So you could technically have a variable called `some_module` and a module called `some_module` and it would be hard to decide just from the import of `some_module` that there shouldn't be a variable of the same name?

I guess we could go further and say that if there is an import of that name and not `with` statement to state the type of the variable with that name and the variable uses dot-access of some kind then we can assume it must be a useful of the module?

Or we introduce some other syntax for value blocks that don't introduce function arguments maybe?

```rust
{> import some_module

{= some_module.function() =}
```
Or something. (Not sure I love that but can't think of anything obvious right now.)

**Comment by michallepicki** [comment]
I personally think requiring all parameters to be declared up-front would be reasonable, to avoid complexity, and let the Gleam compiler figure out the right thing when there are ambiguities

**Comment by lpil** [comment]
I think I would also prefer all parameters to be explicit, I think there's probably quite a lot of tricky edge cases such as the module situation Michael describes which would be challenging to code. It's much simpler to implement the explicit system and I don't see it at being an inferior user experience. It might even help catch typos in some cases as we'll get an undefined variable error.

**Comment by michaeljones** [comment]
So we'd avoid inferring anything and assume that all parameters are stated with "with" statements at the top of the template file?

**Comment by lpil** [comment]
Yes, I think that would be the most straightforward.

Alternatively I think we'd need to restrict the language to not permit arbitrary Gleam expressions and then implement a limited form of type checker in this project to identify where values come from.

**Comment by michaeljones** [comment]
I've put together #14 if you have the time to check it out and assess it at some point.

I suspect it means we can roll back the `{[ name ]}` syntax for StringBuilders as they will be identified by the type given in the corresponding `with` statement (or maybe in a `for ... as ...`.)

Or we could drop the requirement for `as String` and `as StringBuilder` and infer it from the usage syntax but I imagine that is less explicit than we're aiming for here.

I'll probably remove the `{[ name ]}` before merging if I find time over the weekend.

**Comment by michallepicki** [comment]
> Or we could drop the requirement for as String and as StringBuilder and infer it from the usage syntax but I imagine that is less explicit than we're aiming for here.

If I had a vote, I would vote for that (so making parameter types optional, even if that means keeping separate StringBuilder insert syntax)

**Comment by lpil** [comment]
If the string builder interpolation syntax is removed does this mean that the `inner` field of this type can no longer be interpolated? I don't understand how it would know the type of the inner field.

```rust
import gleam/string_builder.{StringBuilder}

pub type SomeArgument {
  SomeArgument(inner: StringBuilder)
}

**Comment by michaeljones** [comment]
Good point! I don't seem to be the best at thinking through the use cases :) We can leave it in. 

@lpil are you in favour of making the `as Type` part of the `with` optional? Or leave it as required?

**Comment by lpil** [comment]
Either or sounds good to me. 👍

**Comment by michaeljones** [comment]
I'll leave it required for the moment and we can revisit in the future.

**Comment by michaeljones** [comment]
This has been resolved in the latest release, I believe.
