### ISSUE TITLE
Find a better file extension

### ISSUE THREAD

**Issue by michaeljones** [michaeljones/gleam-templates#15]
We currently expect templates to use `.gleamx` as the file extension but that feels like it is in the `.jsx` lineage which doesn't reflect this functionality of the tool.

Some languages have an `.elanguage` variant like `.erb` or `.eex` but again that would promise more than we deliver here as we don't support arbitrary embedded gleam code.

I guess we could model it after `.jinja` or some similar template syntax. Either by using `.ginga` as a gleam variant or by using a completely fresh name like the authors of `jinja` chose to do.

I'm also slightly tempted to go for `.glt` as a simple contraction of "gleam templates".

Suggestions & ideas would be welcome!

**Comment by lpil** [comment]
`ginga` is a cute name, makes me think of a red-headed child. I could see a cartoon logo being created to go with it 😁
Though perhaps it sounding the same as `jinja` could be confusing.

Perhaps one for another issue but would you also be open to changing the name of the binary? The name `templates` is quite generic, I might expect a command line tool with that name not be specific to a language.

**Comment by michaeljones** [comment]
Good point about the binary name. I've made #16 for it.

Yeah, I suspect `ginga` is too close to `jinja` in sound and confusing in meaning as it isn't a complete implementation of what jinja does.

**Comment by michaeljones** [comment]
The tool is now called `matcha` and I've used that for the extension too.
