### ISSUE TITLE
Include a comment at the top of generated modules

### ISSUE THREAD

**Issue by lpil** [michaeljones/gleam-templates#21]
Hello!

I was looking at [my project](https://github.com/gleam-lang/example-todomvc/tree/main/src/todomvc/templates) on GitHub and I realised it's not clear that these files are generated, and someone might accidentally edit them.

A comment could help here. In Go it's common to see comments like this:

```go
// Code generated by stringer -type Pill pill.go; DO NOT EDIT.
```

**Comment by michaeljones** [comment]
Good point! Easily done. I'll have a look.

**Comment by michaeljones** [comment]
Done in 0.10.0. Currently looks like:
```rust
// DO NOT EDIT: Code generated by templates from for_as_loop.gleamx
```

**Comment by michaeljones** [comment]
I realise the project name does not help in the parsing of the sentence but hopefully we'll have a better one at some point.

**Comment by lpil** [comment]
Thank you 💜
