### ISSUE TITLE
Fix macOS aarch64 release

### ISSUE THREAD

**Issue by michallepicki** [michaeljones/gleam-templates#23]
There's been a [bug issue](https://github.com/gleam-lang/gleam/issues/1626) opened in the Gleam repository about wrong CPU type in macOS release. Supposedly specifying `default: true` in the `actions-rs/toolchain` is not enough for it to be the picked up when running on the amd64 runner on Github Actions. The release Github Actions workflow in this repository follows the same pattern as the Gleam workflow.

I don't have an Apple M1 device to test this, can someone confirm if it's a problem in the latest [matcha release](https://github.com/michaeljones/matcha/releases/tag/0.13.0)? If so, maybe a [patch](https://github.com/gleam-lang/gleam/pull/1627/files) to the github actions release workflow is needed.

To test it out, please download the [macos `arm64` release](https://github.com/michaeljones/matcha/releases/download/0.13.0/matcha-0.13.0-macos-arm64.tar.gz), extract, and provide what the `file` command returns for it:
```
file matcha
```

**Comment by HarryET** [comment]
Looks like there is the same issue here,
```
➜  Downloads file ./matcha
./matcha: Mach-O 64-bit executable x86_64
➜  Downloads
```
I can however, still run the binary :)

**Comment by michallepicki** [comment]
OK! So I guess means it's working using Rosetta. Thank you! I'll prepare a similar patch here

**Comment by HarryET** [comment]
> OK! So I guess means it's working using Rosetta. Thank you! I'll prepare a similar patch here

Yeah, appears to be what has been happening with gleam for me too.
