### ISSUE TITLE
Do not include unused imports

### ISSUE THREAD

**Issue by lpil** [michaeljones/gleam-templates#25]
Hello!

I'm getting some warnings from the generated files due to unused imports of `gleam/list`. Could we omit this if it is not used? 

Thanks
Louis

**Comment by michaeljones** [comment]
Looks like it should be possible. We only need it if there is a for-loop and it is easy enough to verify if one of those is in the template. I'll have a look soon.

**Comment by michaeljones** [comment]
Thanks for raising it!

**Comment by michaeljones** [comment]
Should be resolved in 0.15.0: https://github.com/michaeljones/matcha/releases/tag/0.15.0

The further these releases grow apart from each other the less confident I am about each one but the tests are good. No reason why it shouldn't all be fine :) Let me know if it isn't.

**Comment by lpil** [comment]
Thank you!
