### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by erooke** [michaeljones/gleam-templates#29]
As it currently stands I cannot find license information in this repository nor can I find anything that suggests this lack of license is intentional.

Without a posted license people are not allowed to distribute, reproduce, or produce derivative works ([source](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license)) based on this code. If this was intentional it might be worth putting a copyright notice somewhere. If it was not intentional it would be nice to have a license posted somewhere.

**Comment by michaeljones** [comment]
Thank you for raising this. Definitely an oversight though perhaps reflective of my increasingly confused feelings about the burden of open source maintainership :sweat_smile: I have added an MIT license file as I would be happy for everyone to use this project.

Thanks again!
