### ISSUE TITLE
Easy installation without compilation

### ISSUE THREAD

**Issue by lpil** [michaeljones/gleam-templates#3]
I could see this tool being super useful in future for rendering HTML, etc. If we get there it would be nice for people to be able to install it easily, either by having it on Hex (possibly after converting it to Gleam?) or by having prebuilt binaries people can download from GitHub.

A bit more of a longer term goal this one, but I thought I'd open an issue anyway :)

**Comment by michaeljones** [comment]
Yeah, I don't have much experience with distributing Rust binaries but I'm happy to learn. Long term I can see the use it in being rewritten in Gleam too.

**Comment by dcrockwell** [comment]
Why was rust chosen for this project instead of gleam?

**Comment by michaeljones** [comment]
@dcrockwell - I was and still am more familiar with Rust than Gleam. Also whilst I've done text parsing with combinators in functional languages, I haven't done this kind of kind of character/grapheme chomping approach in functional languages and don't have an intuitive sense of it. 

I think it would be a plus for the community if a text templating tool was available directly in Gleam but I don't currently have the capacity or motivation to embark on that.

**Comment by dcrockwell** [comment]
All good! Thank you for the thorough response. It was a question of curiosity, and it's not a big deal to install cargo/rust for it :)

Thank you for the tool! We're using it in a production system and appreciating the type safety for our templates.

**Comment by michaeljones** [comment]
Thanks for the response. There are pre-compiled binaries on the releases page if that is an option for you. 

I'm glad the project is providing some value.
